# These are supported funding model platforms
github: [atexcode]  # Replace with your GitHub Sponsors username (if you have one)
custom: 
  - 'mailto:athar.techs@gmail.com'  # Link to open email client with your email addres
